export enum FormControlType {
  INPUT_TEXT = 1,
  INPUT_PASSWORD = 2,
  RADIO = 3,
  CHECKBOX = 4,
  SELECT = 5,
  INPUT_FILE = 6,
  COLOR_PICKER = 7,
  DATE_SELECTOR = 8,
  TEXTAREA = 9,
  CUSTOMIZATION = 10
}
